namespace Olibos.Data.SqlClient.SqlBulkCopy.Tests;

using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

public class SqlBulkCopySourceGeneratorTests
{
    private const string ModelClassText =
        """
        namespace Olibos.Data.SqlClient.SqlBulkCopy.Sample;

        using System;

        [SqlBulkCopy]
        public class Model
        {
            public int Id { get; set; }
            
            public string Name { get; set; }
            
            public DateTime Date { get; set; }
        }
        """;

    private const string ExpectedGeneratedClassText =
        """
        // <auto-generated/>
        namespace Olibos.Data.SqlClient.SqlBulkCopy;

        using System;
        using System.Collections.Generic;
        using System.Threading;
        using System.Threading.Tasks;
        using Microsoft.Data.SqlClient;

        public static partial class SqlBulkCopyExtensions
        {
            public static async Task WriteToServerAsync(this SqlBulkCopy sql, IAsyncEnumerable<global::Olibos.Data.SqlClient.SqlBulkCopy.Sample.Model> items, CancellationToken cancellationToken = default)
            {
                await using var reader = new Olibos_Data_SqlClient_SqlBulkCopy_Sample_Model(items);
                await sql.WriteToServerAsync(reader, cancellationToken).ConfigureAwait(false);
            }
            
            private class Olibos_Data_SqlClient_SqlBulkCopy_Sample_Model(IAsyncEnumerable<global::Olibos.Data.SqlClient.SqlBulkCopy.Sample.Model> enumerable, CancellationToken cancellationToken = default) : BaseAsyncEnumerableReader
            {
                private readonly IAsyncEnumerator<global::Olibos.Data.SqlClient.SqlBulkCopy.Sample.Model> _enumerator = enumerable.GetAsyncEnumerator(cancellationToken);
                
                public override int GetOrdinal(string name)
                    => name switch
                   {
                        "Id" => 0,
                        "Name" => 1,
                        "Date" => 2,

                        _ => throw new ArgumentOutOfRangeException(nameof(name))
                   };
            
                public override object GetValue(int ordinal)
                    => ordinal switch
                   {
                        0 => _enumerator.Current.Id,
                        1 => _enumerator.Current.Name,
                        2 => _enumerator.Current.Date,

                        _ => throw new ArgumentOutOfRangeException(nameof(ordinal))
                   };
            
                public override int FieldCount => 3;
            
                public override ValueTask DisposeAsync() => _enumerator.DisposeAsync();
                
                public override async Task<bool> ReadAsync(CancellationToken cancellationToken)
                    => await _enumerator.MoveNextAsync().ConfigureAwait(false);
            }
        }
        """;

    [Fact]
    public void GenerateWriteToServerAsyncExtension()
    {
        var generator = new SqlBulkCopySourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        var compilation = CSharpCompilation.Create(nameof(SqlBulkCopySourceGenerator),
            [CSharpSyntaxTree.ParseText(ModelClassText)],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);

        var runResult = driver.RunGenerators(compilation).GetRunResult();
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Olibos.Data.SqlClient.SqlBulkCopy.Sample.Model.g.cs"));
        Assert.Equal(
            ExpectedGeneratedClassText,
            generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}